name: CI MLflow

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install mlflow pandas numpy scikit-learn joblib

    - name: Run MLflow Project
      run: |
        mlflow run MLProject

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-artifact
        path: MLProject/outputs/