name: CI MLflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          conda env create -f MLProject/conda.yaml  # Membuat environment dengan conda.yaml

      - name: Run MLflow Project
        run: |
          mlflow run .  # Menjalankan proyek MLflow