name: CI MLflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - run: |
          pip install -r requirements.txt

      - run: |
          cd MLProject
          python modelling.py